# Generated by Django 2.2.4 on 2021-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='content',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mention',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mention',
            name='writer',
            field=models.CharField(max_length=200),
        ),
    ]
