# Generated by Django 2.2.4 on 2021-08-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premain', '0002_auto_20210820_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mention',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mention',
            name='writer',
            field=models.TextField(),
        ),
    ]
