# Generated by Django 2.2.4 on 2021-08-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('writer', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('mbti', models.CharField(max_length=4)),
                ('like_num', models.IntegerField()),
                ('commnet_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('mbti', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('title', models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='main.BookInfo')),
            ],
            options={
                'unique_together': {('title', 'writer')},
            },
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finish', models.IntegerField()),
                ('is_onGoing', models.IntegerField()),
                ('is_reviewed', models.IntegerField()),
                ('book', models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='main.BookInfo')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'unique_together': {('user_id', 'book')},
            },
        ),
    ]
