# Generated by Django 2.2.4 on 2021-08-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob1', models.TextField()),
                ('prob2', models.TextField()),
                ('prob3', models.TextField()),
                ('answer', models.TextField()),
                ('book', models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='main.BookInfo')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
